### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by xylo04** [talios/googleformatter-maven-plugin#14]
I'd love to use this plugin, but my employer requires that all open source dependencies be licensed. Check out https://choosealicense.com/. Maybe MIT would be appropriate?

**Comment by talios** [comment]
My bad - it was always meant to be Apache 2.0 - as that's what the google formatter library is, seems I just never copied the license file into the repo.

Will get on that.

**Comment by talios** [comment]
Cheers!

**Comment by xylo04** [comment]
Thanks!
