### ISSUE TITLE
README lists unsupported configuration flags

### ISSUE THREAD

**Issue by Stephan202** [talios/googleformatter-maven-plugin#6]
The `README` lists the following sample configuration:
```xml
<configuration>
  <includeStale>false</includeStale>
  <maxWidth>160</maxWidth>
  <sortImports>NO</sortImports>
  <javadocFormatter>NONE</javadocFormatter>
  <style>GOOGLE</style>
  <filterModified>true</filterModified>
  <skip>false</skip>
</configuration>
```

However, the options `maxWidth`, `sortImports` and `javadocFormatter` are no longer supported. Do you plan to reintroduce these?

**Comment by talios** [comment]
Ahhh no - I should remove them. I had an open PR with the upstream project to re-enable support for it since it's still in their public API, just no longer used, but they never accepted the patch as they don't want ANY form of config.

**Comment by Stephan202** [comment]
Ack. Unfortunate, but it is what it is. I filed #7 so that all you have to do is press a button :).
